python3.6 baseline_fm_tf.py --fm_order=1 --fm_rank=2 --fm_epoch=10 --fm_reg=0.00001 --fm_featconfig=champion_two_teams
python3.6 baseline_fm_tf.py --fm_order=1 --fm_rank=2 --fm_epoch=10 --fm_reg=0.0001 --fm_featconfig=champion_two_teams
python3.6 baseline_fm_tf.py --fm_order=1 --fm_rank=2 --fm_epoch=10 --fm_reg=0.001 --fm_featconfig=champion_two_teams
python3.6 baseline_fm_tf.py --fm_order=1 --fm_rank=2 --fm_epoch=10 --fm_reg=0.01 --fm_featconfig=champion_two_teams
python3.6 baseline_fm_tf.py --fm_order=1 --fm_rank=2 --fm_epoch=10 --fm_reg=0.1 --fm_featconfig=champion_two_teams
python3.6 baseline_fm_tf.py --fm_order=1 --fm_rank=2 --fm_epoch=10 --fm_reg=1.0 --fm_featconfig=champion_two_teams
python3.6 baseline_fm_tf.py --fm_order=1 --fm_rank=2 --fm_epoch=10 --fm_reg=10 --fm_featconfig=champion_two_teams
python3.6 baseline_fm_tf.py --fm_order=1 --fm_rank=2 --fm_epoch=10 --fm_reg=100 --fm_featconfig=champion_two_teams
python3.6 baseline_fm_tf.py --fm_order=1 --fm_rank=2 --fm_epoch=10 --fm_reg=1000 --fm_featconfig=champion_two_teams
python3.6 baseline_fm_tf.py --fm_order=1 --fm_rank=2 --fm_epoch=10 --fm_reg=10000 --fm_featconfig=champion_two_teams
python3.6 baseline_fm_tf.py --fm_order=1 --fm_rank=2 --fm_epoch=10 --fm_reg=0.00001 --fm_featconfig=summoner_two_teams
python3.6 baseline_fm_tf.py --fm_order=1 --fm_rank=2 --fm_epoch=10 --fm_reg=0.0001 --fm_featconfig=summoner_two_teams
python3.6 baseline_fm_tf.py --fm_order=1 --fm_rank=2 --fm_epoch=10 --fm_reg=0.001 --fm_featconfig=summoner_two_teams
python3.6 baseline_fm_tf.py --fm_order=1 --fm_rank=2 --fm_epoch=10 --fm_reg=0.01 --fm_featconfig=summoner_two_teams
python3.6 baseline_fm_tf.py --fm_order=1 --fm_rank=2 --fm_epoch=10 --fm_reg=0.1 --fm_featconfig=summoner_two_teams
python3.6 baseline_fm_tf.py --fm_order=1 --fm_rank=2 --fm_epoch=10 --fm_reg=1.0 --fm_featconfig=summoner_two_teams
python3.6 baseline_fm_tf.py --fm_order=1 --fm_rank=2 --fm_epoch=10 --fm_reg=10 --fm_featconfig=summoner_two_teams
python3.6 baseline_fm_tf.py --fm_order=1 --fm_rank=2 --fm_epoch=10 --fm_reg=100 --fm_featconfig=summoner_two_teams
python3.6 baseline_fm_tf.py --fm_order=1 --fm_rank=2 --fm_epoch=10 --fm_reg=1000 --fm_featconfig=summoner_two_teams
python3.6 baseline_fm_tf.py --fm_order=1 --fm_rank=2 --fm_epoch=10 --fm_reg=10000 --fm_featconfig=summoner_two_teams
